Repository materializecss/materialize, pull requests merged in 2020-09, with the labels that each got.

#22 Chips autocomplete should have option to prevent user own input
  jade/page-contents/chips_content.html
  js/chips.js
Labels: enhancement

#24 revert blur and focus on last chip delete
  js/chips.js
Labels: bugfix

#25 Updated quickstart cdn
  README.md
Labels: documentation

#28 Fix Gruntfile.js to prevent erroneous replace
  Gruntfile.js
Labels: build

#34 Fix the style of the input field for chips
  sass/components/_chips.scss
Labels: bugfix, component: chips

#19 Add default options argument to sidebar documentation
  jade/page-contents/autocomplete_content.html
  jade/page-contents/carousel_content.html
  jade/page-contents/chips_content.html
  jade/page-contents/collapsible_content.html
  jade/page-contents/dropdown_content.html
  jade/page-contents/featureDiscovery_content.html
  jade/page-contents/floating-action-button-content.html
  jade/page-contents/media_content.html
  jade/page-contents/modals_content.html
  jade/page-contents/navbar_content.html
  jade/page-contents/parallax_content.html
  jade/page-contents/pickers_content.html
  jade/page-contents/pushpin_content.html
  jade/page-contents/scrollspy_content.html
  jade/page-contents/select_content.html
  jade/page-contents/sidenav_content.html
  jade/page-contents/tooltips_content.html
Labels: documentation

#30 Update readme to describe building
  README.md
  package.json
Labels: documentation

#32 Revert "Refactored sidenav css to accommodate btns better"
  sass/components/_sidenav.scss
Labels: bugfix, component: sidenav
