Repository materializecss/materialize, pull requests merged in 2021-04, with the labels that each got.

#105 add copy code button
  docs/js/init.js
  jade/getting_started/getting_started_content.html
Labels: documentation, enhancement

#87 #6279: fixed aligning of dropdown with coverTrigger=false, when can align bottom
  js/dropdown.js
Labels: bugfix, component: dropdown

#112 Fix issue with Feature Discovery
  js/tapTarget.js
Labels: bugfix, css
